  version: '3.8'

  services:
    db:
      image: mysql:8.2.0
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "3307:3307"
      volumes:
        - db:/var/lib/mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      security_opt:
        - seccomp:unconfined
    backend:
      build:
        context: ./backend/
        dockerfile: Dockerfile
      stdin_open: true
      tty: true
      volumes:
        - ./backend:/myapp
      command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
      depends_on:
        - db
      ports:
        - "8080:8080"
      environment:
        TZ: Asia/Tokyo
    frontend:
      build:
        context: ./frontend/
        dockerfile: Dockerfile
      volumes:
        - ./frontend/app:/front
      command: sh -c "npm install && npm start"
      ports:
        - "3000:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true
  volumes:
    db:
      driver: local
    bundle:
      driver: local
